language: csharp
solution: ./OpenAI/OpenAI.sln
install:
  - nuget restore ./OpenAI/OpenAI.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Debug ./OpenAI/OpenAI.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./OpenAI/OpenAI/bin/Debug/OpenAI.dll